name: continuous-integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: using node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.
      - name: install dependencies, run build and run test
        run: |
          npm install
          npm run build
      - name: deploy firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
