name: continuous-integration

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: using node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.
      - name: install dependencies, run build and run test
        run: |
          npm install
          npm install -g firebase-tools
          npm run build
          npm run test
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
